services:
  - type: web
    name: harmonic-universe
    runtime: python
    buildCommand: |
      # Install Python dependencies from correct location
      cd backend && python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      # Make sure gunicorn is installed
      python -m pip install gunicorn
      # Build the React frontend
      cd ../frontend && npm install && npm run render-build
      # Copy built frontend to Flask static directory
      cd ..
      mkdir -p static
      cp -r frontend/dist/* static/
      # Make sure the polyfill script is copied
      cp frontend/public/react-polyfill.js static/
      # Also copy any other important scripts
      cp frontend/public/react-context-provider.js static/ 2>/dev/null || true
      # Run our script to copy polyfill to Flask static directory
      cd backend && python -m scripts.copy_react_polyfill
      # Run the verify imports script to debug any potential issues
      cd /opt/render/project/src && python -c "import sys; sys.path.append('/opt/render/project/src'); sys.path.append('/opt/render/project/src/backend'); from backend.scripts.verify_imports import *"
      # Verify app can be imported (for debugging)
      cd /opt/render/project/src && python -m backend.scripts.verify_app
    startCommand: cd /opt/render/project/src/backend && PYTHONPATH=/opt/render/project/src:/opt/render/project/src/backend gunicorn --chdir /opt/render/project/src/backend wsgi:app
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: CI
        value: 'false'
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        generateValue: true
      - key: SCHEMA
        value: harmonic_universe_schema
      - key: PYTHONUNBUFFERED
        value: 'true'
      - key: PYTHONPATH
        value: '/opt/render/project/src:/opt/render/project/src/backend'
      - key: REACT_APP_BASE_URL
        value: 'https://harmonic-universe.onrender.com'
      - key: DATABASE_URL
        fromDatabase:
          name: harmonic-universe-db
          property: connectionString

databases:
  - name: harmonic-universe-db
    plan: starter
