name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Harmonic Universe'
          path: '.'
          format: 'HTML'
          args: >
            --scan .
            --suppression ./.dependency-check-suppression.xml
            --failOnCVSS 7
            --enableRetired

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            snyk-results.json
            dependency-check-report.html
            trivy-results.json

      - name: Notify on High Severity
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 High Severity Security Vulnerabilities Detected',
              body: 'Security scan has detected high severity vulnerabilities. Please check the security scan results.'
            })
