version: 1
buildCommand: chmod +x render-deploy.sh && ROLLUP_SKIP_NODEJS_NATIVE_BUILD=true NODE_ENV=production ./render-deploy.sh
startCommand: cd backend && gunicorn --workers=2 --timeout=120 --log-level info wsgi:app
