# Render.com configuration
services:
  # For a static site (no server needed)
  - type: web
    name: harmonic-universe-static
    runtime: static
    buildCommand: cd frontend && npm install && npm run render-build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: CI
        value: 'false'

  # For a Node.js service (with server)
  - type: web
    name: harmonic-universe-web
    runtime: node
    buildCommand: cd frontend && npm install && npm run render-build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: CI
        value: 'false'
      - key: PORT
        value: 10000
