runtime: python39

handlers:
  - url: /health
    static_files: public/health
    upload: public/health
    mime_type: application/json

  - url: /api/health
    static_files: public/api/health
    upload: public/api/health
    mime_type: application/json

  - url: /static
    static_dir: public/static

  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)

  - url: /
    static_files: public/index.html
    upload: public/index.html
