"""
Root-level app.py to fix import issues on Render.com
This file provides a clean entry point for gunicorn
"""
import os
import sys
import glob
import logging
from flask import Flask, send_from_directory, current_app, make_response, jsonify, request, abort, send_file, Response
import traceback
from datetime import datetime
from config import current_config
from werkzeug.middleware.proxy_fix import ProxyFix

# Add the current directory to Python path to ensure imports work correctly
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def create_app():
    """
    Factory function that creates and returns the Flask application.
    This avoids circular imports by importing the actual app inside the function.
    """
    try:
        # Apply configuration
        app = Flask(__name__, static_folder='static')
        app.config.update(current_config.get_config())

        # Fix for proxy headers from Render
        app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)

        # Ensure static folder exists
        os.makedirs(app.static_folder, exist_ok=True)

        # Log static folder information
        logger.info(f"Static folder path: {os.path.abspath(app.static_folder)}")
        if os.path.exists(app.static_folder):
            files = os.listdir(app.static_folder)
            logger.info(f"Static folder contains {len(files)} files: {', '.join(files)}")
        else:
            logger.warning(f"Static folder doesn't exist: {app.static_folder}")

        # Create emergency index.html if it doesn't exist
        index_html_path = os.path.join(app.static_folder, 'index.html')
        if not os.path.exists(index_html_path) or os.path.getsize(index_html_path) == 0:
            logger.warning("index.html missing or empty, creating emergency version")
            with open(index_html_path, 'w') as f:
                f.write("""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Harmonic Universe</title>
    <style>
        body { font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; padding: 40px; line-height: 1.5; }
        .container { max-width: 800px; margin: 0 auto; background: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #333; }
        p { color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Harmonic Universe</h1>
        <p>Welcome to Harmonic Universe. This is an emergency page generated by the application.</p>
        <p>If you're seeing this page, it means the application is running correctly but there was an issue with the static files.</p>
    </div>
</body>
</html>""")

        # Enable debug mode for more verbose errors
        app.config['DEBUG'] = True

        # Define a direct health check endpoint at the root level
        @app.route('/api/health')
        def health_check():
            logger.info("Health check endpoint accessed")
            try:
                # Get static file information
                static_files = []
                if os.path.exists(app.static_folder):
                    static_files = os.listdir(app.static_folder)

                # Get basic system information
                import psutil
                memory_info = psutil.virtual_memory()

                return jsonify({
                    "status": "ok",
                    "version": os.environ.get("APP_VERSION", "1.0.0"),
                    "environment": os.environ.get("FLASK_ENV", "production"),
                    "render_instance": os.environ.get("RENDER_INSTANCE_ID", "unknown"),
                    "static_folder": os.path.abspath(app.static_folder),
                    "static_files": static_files,
                    "system": {
                        "memory_used_percent": memory_info.percent,
                        "cpu_percent": psutil.cpu_percent(interval=0.1)
                    }
                })
            except Exception as e:
                logger.error(f"Error in health check: {str(e)}")
                return jsonify({
                    "status": "error",
                    "error": str(e)
                }), 500

        # Define a route for assets
        @app.route('/assets/<path:filename>')
        def serve_assets(filename):
            logger.info(f"Serving asset: {filename}")
            asset_path = os.path.join(app.static_folder, 'assets', filename)
            if os.path.exists(asset_path):
                return send_file(asset_path)
            else:
                logger.warning(f"Asset not found: {filename}")
                abort(404)

        # Special route handler for all potential React routes
        @app.route('/', defaults={'path': ''})
        @app.route('/<path:path>')
        def catch_all(path):
            # Skip API routes
            if path.startswith('api/'):
                return 'Not Found', 404

            # Log request details
            logger.info(f"Catch-all route for: {path}")

            # Check if file exists in static folder
            file_path = os.path.join(app.static_folder, path)
            if os.path.exists(file_path) and os.path.isfile(file_path):
                logger.info(f"Serving existing file: {path}")
                return send_from_directory(app.static_folder, path)

            # For all other paths not found, serve index.html for client-side routing
            logger.info(f"Path {path} not found, serving index.html for client-side routing")
            return send_from_directory(app.static_folder, 'index.html')

        # Now try to import and use the backend app
        try:
            from backend.app import create_app as backend_create_app
            from backend.app.core.config import config
            from backend.middleware import log_request_errors

            # Register backend routes
            logger.info("Importing backend routes")
            from backend.app.api import api_bp
            app.register_blueprint(api_bp, url_prefix='/api/v1')

            # Initialize middleware
            log_request_errors(app)

            logger.info("Backend routes successfully registered")
        except Exception as e:
            logger.warning(f"Could not import backend app: {str(e)}")
            logger.warning("Continuing with minimal Flask app")

        # Add security headers middleware
        @app.after_request
        def add_security_headers(response):
            # Basic CSP to protect against XSS attacks
            response.headers['Content-Security-Policy'] = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;"
            # Prevent MIME type sniffing
            response.headers['X-Content-Type-Options'] = 'nosniff'
            # Prevent clickjacking
            response.headers['X-Frame-Options'] = 'SAMEORIGIN'
            # Enable browser XSS protection
            response.headers['X-XSS-Protection'] = '1; mode=block'
            return response

        # Error logging middleware
        @app.errorhandler(Exception)
        def handle_exception(e):
            app.logger.error(f"Unhandled exception: {str(e)}")
            app.logger.error(traceback.format_exc())
            return "Internal Server Error", 500

        # Update your serve_static function
        @app.route('/<path:path>')
        def serve_static(path):
            """Serve static files or fallback to index.html for client-side routing"""
            try:
                if os.path.exists(os.path.join(app.static_folder, path)):
                    logger.info(f"Serving static file: {path}")
                    return send_from_directory(app.static_folder, path)
                elif '.' not in path:  # No file extension, likely a route
                    logger.info(f"Path {path} not found, serving index.html (SPA routing)")
                    return send_from_directory(app.static_folder, 'index.html')
                else:
                    logger.warning(f"File not found: {path}")
                    return "File not found", 404
            except Exception as e:
                logger.error(f"Error serving {path}: {str(e)}")
                logger.error(traceback.format_exc())
                return "Internal Server Error", 500

        return app
    except Exception as e:
        import traceback
        logger.error(f"Error creating app: {e}")
        logger.error(traceback.format_exc())

        # Create a minimal emergency app if everything else fails
        minimal_app = Flask(__name__)

        @minimal_app.route('/')
        def minimal_index():
            return "Minimal emergency Flask app is running. There was an error creating the full app."

        @minimal_app.route('/api/health')
        def minimal_health():
            return jsonify({
                "status": "degraded",
                "message": "Minimal emergency app is running due to errors",
                "error": str(e)
            })

        return minimal_app

# Create a global app instance if not already defined
if 'app' not in globals():
    try:
        from app import create_app  # Import your factory function
        app = create_app()  # Create the app
    except ImportError:
        print("Error: Cannot find create_app function")
        sys.exit(1)

# Run the application when executed directly
if __name__ == "__main__":
    try:
        # Get port from environment with fallback
        port = int(os.environ.get("PORT", 10000))
        print(f"Starting app on port {port}")
        app.run(host="0.0.0.0", port=port)
    except Exception as e:
        print(f"Error starting application: {e}")
        traceback.print_exc()
        sys.exit(1)
