version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=harmonic_universe
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    environment:
      - FLASK_APP=backend/run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/harmonic_universe
      - SECRET_KEY=dev-key-please-change-in-production
      - JWT_SECRET_KEY=jwt-secret-key-change-in-production
      - PORT=5001
      - LOG_LEVEL=DEBUG
      - AUTO_CREATE_TABLES=True
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
      - ENABLE_MFA=False
      - ENABLE_PASSWORD_RESET=True
      - ENABLE_ACCOUNT_LOCKOUT=True
      - ENABLE_DEBUG_LOGGING=True
      - MOCK_AUTH_IN_DEV=False
      - DEMO_MODE=False
      - OFFLINE_MODE=True
      - DEBUG_MODE=True
      - ANALYTICS=False
      - PERFORMANCE_MONITORING=False
    volumes:
      - ./backend:/app/backend
      - ./backend/static:/app/backend/static
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend

volumes:
  postgres_data:
