services:
  # Backend service
  - type: web
    name: harmonic-universe
    env: python
    plan: starter
    buildCommand: ./scripts/build.sh
    startCommand: ./scripts/start.sh
    healthCheckPath: /api/health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.0.0
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.production
    autoDeploy: true

  # Frontend service
  - type: web
    name: harmonic-universe-frontend
    runtime: node
    region: oregon # Choose your preferred region
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: 'https://harmonic-universe-x84a.onrender.com/api'

databases:
  - name: harmonic-universe-db
    plan: free
