services:
  - type: web
    name: harmonic-universe
    runtime: python
    buildCommand: ./build.sh
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: FLASK_ENV
        value: production
      # Add any other environment variables your app needs
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: harmonic-universe-db
      #     property: connectionString
# If you need a database
# databases:
#  - name: harmonic-universe-db
#    plan: free
