services:
  - type: web
    name: harmonic-universe
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: starter
    envVars:
      - key: FLASK_APP
        value: backend.app:create_app
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.18.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: DEPLOYMENT_PLATFORM
        value: render
      - key: VITE_API_BASE_URL
        value: /api
      - key: API_BASE_URL
        value: /api
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: VITE_APP_ENV
        value: production
      - key: VITE_BUILD_PATH
        value: dist
      - key: VITE_USE_HASH_ROUTER
        value: "true"
      - key: VITE_ROUTER_BASE
        value: "/"
      - key: ROLLUP_SKIP_NODEJS_NATIVE_BUILD
        value: "true"
      - key: ROLLUP_NATIVE_PURE_JS
        value: "true"
      - key: ROLLUP_DISABLE_NATIVE
        value: "true"
      - key: LOG_LEVEL
        value: DEBUG
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENABLE_DETAILED_LOGGING
        value: "true"
      - key: STATIC_URL_PATH
        value: ""
      - key: STATIC_FOLDER
        value: "/opt/render/project/src/backend/app/static"
      - key: REACT_APP_API_URL
        value: /api
      - key: RENDER
        value: "true"
      - fromGroup: harmonic-universe-env
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: harmonic_universe_db
    plan: free
    postgresMajorVersion: 15

envVarGroups:
  - name: harmonic-universe-env
    envVars:
      - key: DATABASE_URL
        value: ${harmonic_universe_db.connectionString}
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://harmonic-universe.onrender.com,https://harmonic-universe-z5ka.onrender.com,*
