# render.yaml
services:
  - type: web
    name: harmonic-universe
    runtime: python
    buildCommand: |
      # Build frontend
      cd frontend && npm install && npm run build && cd ..
      # Build backend
      python -m pip install --upgrade pip
      python -m pip install -r backend/requirements.txt
      python -m pip install psycopg2
      python -m pip install gunicorn==21.2.0
      echo "Installed packages:"
      python -m pip list
      cd backend && python -m flask db upgrade
      cd backend && python -m flask seed all
    startCommand: 'cd /opt/render/project/src && python -m gunicorn --chdir backend app.main:app --log-level debug'
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: backend/app
      - key: SECRET_KEY
        generateValue: true
      - key: SCHEMA
        value: harmonic_universe_schema
      - key: PYTHONUNBUFFERED
        value: 'true'
      - key: PYTHONPATH
        value: '/opt/render/project/src:/opt/render/project/src/backend'
      - key: REACT_APP_BASE_URL
        fromService:
          name: harmonic-universe
          type: web
          property: origin
      - key: DATABASE_URL
        fromDatabase:
          name: harmonic-universe-db
          property: connectionString

databases:
  - name: harmonic-universe-db
    plan: starter
