#!/bin/bash
set -e

echo "=== Starting Render Build Process ==="
echo "Date: $(date)"
echo "Python version: $(python --version)"
echo "Current directory: $(pwd)"
echo "Python executable: $(which python)"

# Set environment variables for PostgreSQL
export PGCONNECT_TIMEOUT=10
export PGSSLMODE=require

# Install system dependencies - PostgreSQL client libraries
echo "Installing system dependencies..."
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    libpq-dev \
    postgresql-client \
    build-essential \
    python3-dev \
    netcat \
    curl \
    python3-venv

# Clean up apt cache to reduce image size
apt-get clean
rm -rf /var/lib/apt/lists/*

# Check for virtual environment and activate it if exists
VENV_PATH="/opt/render/project/src/.venv"
if [ -d "$VENV_PATH" ]; then
    echo "Virtual environment detected at $VENV_PATH"
    echo "Activating virtual environment..."
    source "$VENV_PATH/bin/activate"
    echo "Using Python: $(which python)"
    echo "Using pip: $(which pip)"
else
    echo "No virtual environment found at $VENV_PATH - creating one"
    python -m venv .venv
    source .venv/bin/activate
    echo "Created and activated new virtual environment"
    echo "Using Python: $(which python)"
    echo "Using pip: $(which pip)"
fi

# Ensure pip is up to date
echo "Upgrading pip in virtual environment..."
python -m pip install --upgrade pip

# Install critical dependencies first
echo "Installing critical dependencies..."
python -m pip install --no-cache-dir Flask==2.0.1
python -m pip install --no-cache-dir Werkzeug==2.0.1
python -m pip install --no-cache-dir psycopg2-binary==2.9.9
python -m pip install --no-cache-dir gunicorn==20.1.0

# Verify gunicorn is installed and in PATH
if which gunicorn > /dev/null; then
    echo "Gunicorn is installed and in PATH: $(which gunicorn)"
    gunicorn --version
else
    echo "WARNING: Gunicorn not found in PATH after installation"
    echo "Attempting alternative installation..."
    python -m pip install --no-cache-dir gunicorn==20.1.0
    python -m gunicorn --version || echo "Failed to run gunicorn even after reinstall"
fi

# Install remaining Python dependencies
echo "Installing remaining dependencies..."
python -m pip install --no-cache-dir -r requirements.txt

# Verify critical packages
echo "Verifying critical packages..."
python -c "import flask; print('Flask version:', flask.__version__)" || echo "Error: Flask import failed"
python -c "import psycopg2; print('Psycopg2 version:', psycopg2.__version__)" || echo "Error: Psycopg2 import failed"
python -c "import sys; print('Python path:', sys.path)" || echo "Error: Cannot print Python path"

# List installed packages for debugging
echo "Installed packages:"
python -m pip list

# Create a marker file to indicate successful dependency installation
echo "Creating dependency marker file..."
echo "Dependencies installed on $(date)" > .deps_installed

# Handle static files
echo "=== Setting up static files ==="
STATIC_DIR="static"

# Ensure static directory exists
if [ -d "$STATIC_DIR" ]; then
    echo "Static directory exists at $(pwd)/$STATIC_DIR"
    echo "Contents of static directory:"
    ls -la "$STATIC_DIR"
else
    echo "WARNING: Static directory does not exist, creating it"
    mkdir -p "$STATIC_DIR"
fi

# Ensure there's an index.html file in static
if [ -f "$STATIC_DIR/index.html" ]; then
    echo "index.html exists in static directory"
else
    echo "WARNING: index.html not found in static directory, creating a basic one"
    cat > "$STATIC_DIR/index.html" << EOF
<!DOCTYPE html>
<html>
<head>
    <title>Harmonic Universe</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        h1 { color: #333; }
        .container { max-width: 800px; margin: 0 auto; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Harmonic Universe</h1>
        <p>Application is running! This is a fallback page generated by the build script.</p>
        <div id="api-status">Checking API status...</div>
    </div>
    <script>
        fetch('/api/health')
            .then(response => response.json())
            .then(data => {
                document.getElementById('api-status').innerHTML =
                    'API Status: <span style="color:' + (data.status === 'healthy' ? 'green' : 'red') + '">' + data.status + '</span>';
            })
            .catch(error => {
                document.getElementById('api-status').innerHTML =
                    'API Status: <span style="color:red">Connection Failed</span>';
            });
    </script>
</body>
</html>
EOF
fi

# Create debug script
echo "Creating debug.js in static directory"
cat > "$STATIC_DIR/debug.js" << EOF
// Debug file to verify static asset serving
console.log('Debug script loaded successfully!');

// Create a visible indicator on the page
document.addEventListener('DOMContentLoaded', function() {
  const debugElement = document.createElement('div');
  debugElement.style.position = 'fixed';
  debugElement.style.bottom = '10px';
  debugElement.style.right = '10px';
  debugElement.style.padding = '10px';
  debugElement.style.background = 'green';
  debugElement.style.color = 'white';
  debugElement.style.borderRadius = '5px';
  debugElement.style.zIndex = '9999';
  debugElement.textContent = 'Debug: Static files working!';
  document.body.appendChild(debugElement);

  // Add API status check
  fetch('/api/health')
    .then(response => response.json())
    .then(data => {
      const apiElement = document.createElement('div');
      apiElement.style.position = 'fixed';
      apiElement.style.bottom = '60px';
      apiElement.style.right = '10px';
      apiElement.style.padding = '10px';
      apiElement.style.background = data.status === 'healthy' ? 'green' : 'red';
      apiElement.style.color = 'white';
      apiElement.style.borderRadius = '5px';
      apiElement.style.zIndex = '9999';
      apiElement.textContent = "API Status: " + data.status;
      document.body.appendChild(apiElement);
    })
    .catch(error => {
      console.error('API health check failed:', error);
      const apiElement = document.createElement('div');
      apiElement.style.position = 'fixed';
      apiElement.style.bottom = '60px';
      apiElement.style.right = '10px';
      apiElement.style.padding = '10px';
      apiElement.style.background = 'red';
      apiElement.style.color = 'white';
      apiElement.style.borderRadius = '5px';
      apiElement.style.zIndex = '9999';
      apiElement.textContent = 'API Status: Connection Failed';
      document.body.appendChild(apiElement);
    });
});
EOF

# Create version-patch.js
echo "Creating version-patch.js in static directory"
cat > "$STATIC_DIR/version-patch.js" << EOF
// Simple version patch script
console.log('Version patch script loaded');

// Define any required globals to prevent errors
window.__ENV__ = window.__ENV__ || {};
window.__ENV__.API_URL = window.location.origin;
window.__VERSION__ = '1.0.0';
EOF

# Create a simple favicon if needed
if [ ! -f "$STATIC_DIR/favicon.ico" ] && [ ! -f "$STATIC_DIR/favicon.svg" ]; then
    echo "Creating a simple favicon in static directory"
    cat > "$STATIC_DIR/favicon.svg" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<svg width="32" height="32" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" style="stop-color:#4A90E2;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#50E3C2;stop-opacity:1" />
        </linearGradient>
    </defs>
    <circle cx="16" cy="16" r="14" fill="none" stroke="url(#grad1)" stroke-width="2"/>
    <circle cx="16" cy="16" r="8" fill="none" stroke="url(#grad1)" stroke-width="1.5"/>
    <circle cx="16" cy="16" r="3" fill="url(#grad1)"/>
</svg>
EOF
fi

# Create assets directory if it doesn't exist
if [ ! -d "$STATIC_DIR/assets" ]; then
    echo "Creating assets directory in static"
    mkdir -p "$STATIC_DIR/assets"

    # Create a minimal CSS file to verify assets loading
    cat > "$STATIC_DIR/assets/minimal.css" << EOF
/* Minimal CSS for verification */
body {
  background-color: #f9f9f9;
  color: #333;
}
EOF

    # Create a minimal JS file to verify assets loading
    cat > "$STATIC_DIR/assets/minimal.js" << EOF
// Minimal JS for verification
console.log('Minimal asset JS loaded successfully');
EOF
fi

# Set proper permissions for static directory
echo "Setting permissions for static directory"
chmod -R 755 "$STATIC_DIR"

# Verify static files
echo "=== Static Files Setup Complete ==="
echo "Static directory structure:"
ls -la "$STATIC_DIR"
echo "Static assets directory:"
ls -la "$STATIC_DIR/assets" || echo "Assets directory not found"

# Make db_connect.sh executable if it exists
if [ -f "db_connect.sh" ]; then
    chmod +x db_connect.sh
    echo "Testing database connection with db_connect.sh..."
    # Run but don't fail the build if it fails
    ./db_connect.sh || echo "Database connection test failed, but continuing build"
else
    echo "Creating emergency database connection test..."
    cat > db_test.py << EOF
#!/usr/bin/env python
import os
import sys
import time

def test_connection():
    url = os.environ.get('DATABASE_URL')
    if not url:
        print("No DATABASE_URL environment variable found")
        return False

    for adapter in ['psycopg2', 'pg8000', 'psycopg']:
        try:
            print(f"Trying {adapter}...")
            if adapter == 'psycopg2':
                import psycopg2
                conn = psycopg2.connect(url)
            elif adapter == 'pg8000':
                import pg8000.native
                conn = pg8000.native.Connection(url)
            elif adapter == 'psycopg':
                import psycopg
                conn = psycopg.connect(url)

            cursor = conn.cursor()
            cursor.execute('SELECT 1')
            print(f"{adapter} connection successful!")
            conn.close()
            return True
        except Exception as e:
            print(f"{adapter} connection error: {e}")

    return False

# Retry logic
retries = 3
for i in range(retries):
    print(f"Connection attempt {i+1}/{retries}")
    if test_connection():
        sys.exit(0)
    if i < retries - 1:
        print(f"Retrying in 5 seconds...")
        time.sleep(5)

print("All connection attempts failed")
# Don't fail the build
sys.exit(0)
EOF
    chmod +x db_test.py
    python db_test.py
fi

echo "=== Build Complete ==="
