services:
  - type: web
    name: harmonic-universe
    env: python
    buildCommand: |
      cd backend && \
      pip install -r requirements.txt && \
      export FLASK_APP=app.py && \
      export PYTHONPATH=$PYTHONPATH:$(pwd) && \
      if [ -n "$DATABASE_URL" ]; then \
        python -c "
        import time
        from app import app, db
        time.sleep(5)  # Wait for DB to be ready
        with app.app_context():
            db.create_all()
        "
      else \
        echo "DATABASE_URL not set, skipping db setup"
      fi && \
      cd ../frontend && \
      npm install && \
      npm run build
    startCommand: cd backend && gunicorn --workers=2 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHON_VERSION
        value: 3.11.0
      - fromGroup: harmonic-universe-env
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: harmonic_universe_db
    plan: free
    postgresMajorVersion: 15

envVarGroups:
  - name: harmonic-universe-env 