services:
  - type: web
    name: harmonic-universe
    env: python
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 16.20.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: VITE_API_BASE_URL
        value: https://harmonic-universe.onrender.com
      - fromGroup: harmonic-universe-env
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: harmonic_universe_db
    plan: free
    postgresMajorVersion: 15

envVarGroups:
  - name: harmonic-universe-env
    envVars:
      - key: DATABASE_URL
        value: ${harmonic_universe_db.connectionString}
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://harmonic-universe.onrender.com
