services:
  - type: web
    name: harmonic-universe
    env: python
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
    plan: starter
    envVars:
      - key: FLASK_APP
        value: backend.app:create_app
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.18.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: DEPLOYMENT_PLATFORM
        value: render
      - key: VITE_API_BASE_URL
        value: https://harmonic-universe.onrender.com
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: LOG_LEVEL
        value: DEBUG
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENABLE_DETAILED_LOGGING
        value: "true"
      - fromGroup: harmonic-universe-env
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: harmonic_universe_db
    plan: free
    postgresMajorVersion: 15

envVarGroups:
  - name: harmonic-universe-env
    envVars:
      - key: DATABASE_URL
        value: ${harmonic_universe_db.connectionString}
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://harmonic-universe.onrender.com
