# Exported from Render on 2025-04-08T01:29:23Z
services:
  - type: web
    name: Harmonic-Universe
    runtime: python
    repo: https://github.com/JeyHightower/Harmonic-Universe
    branch: deploy-2
    plan: free
    envVars:
      - key: SCHEMA
        sync: false
      - key: FLASK_APP
        value: "backend/wsgi.py"
      - key: DATABASE_URL
        fromDatabase:
          name: harmonic-universe-db
          property: connectionString
      - key: PYTHONPATH
        value: "."
      - key: PYTHON_VERSION
        sync: false
      - key: PORT
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"
      - key: FLASK_ENV
        value: "production"
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: STATIC_URL_PATH
        value: "/"
      - key: STATIC_FOLDER
        value: "backend/static"
      - key: NODE_VERSION
        value: "18.16.0"
      - key: VITE_API_URL
        value: "https://harmonic-universe-z5ka.onrender.com/api"
    region: ohio
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: |
      cd backend && gunicorn --worker-class eventlet -w 1 wsgi:app

  # PostgreSQL Database
  - type: pserv
    name: harmonic-universe-db
    plan: free
    region: ohio
    env: postgresql
    disk:
      name: database-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

databases:
  - name: harmonic-universe-db
    plan: free
    region: ohio
    databaseName: harmonic_universe
    user: harmonic_user
    ipAllowList: [] # Allow connections from all IPs

version: "1"
