#!/usr/bin/env python
# wsgi_wrapper.py - A wrapper that ensures dependencies are available

import os
import sys
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("wsgi_wrapper")

logger.info("Starting wsgi_wrapper.py")
logger.info(f"Current directory: {os.getcwd()}")
logger.info(f"Python path: {sys.path}")

# Add current directory to Python path
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)
    logger.info(f"Added {current_dir} to Python path")

# Verify dependencies
try:
    import flask
    logger.info(f"Found Flask: {flask.__version__}")
    import psycopg2
    logger.info(f"Found psycopg2: {psycopg2.__version__}")
except ImportError as e:
    logger.error(f"Missing dependency: {e}")
    raise ImportError(f"Critical dependency missing: {e}")

# Create debug static content as fallback
static_dir = os.path.join(current_dir, 'static')
if not os.path.exists(static_dir):
    logger.info(f"Creating static directory at {static_dir}")
    os.makedirs(static_dir, exist_ok=True)

    # Create basic index.html if it doesn't exist
    index_path = os.path.join(static_dir, 'index.html')
    if not os.path.exists(index_path):
        logger.info(f"Creating fallback index.html at {index_path}")
        with open(index_path, 'w') as f:
            f.write("""<!DOCTYPE html>
<html>
<head>
    <title>Harmonic Universe</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
        h1 { color: #333; }
        .container { max-width: 800px; margin: 0 auto; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Harmonic Universe</h1>
        <p>Application is running! This is a fallback page generated by wsgi_wrapper.py.</p>
        <div id="api-status">Checking API status...</div>
    </div>
    <script>
        fetch('/api/health')
            .then(response => response.json())
            .then(data => {
                document.getElementById('api-status').innerHTML =
                    `API Status: <span style="color:${data.status === 'healthy' ? 'green' : 'red'}">${data.status}</span>`;
            })
            .catch(error => {
                document.getElementById('api-status').innerHTML =
                    `API Status: <span style="color:red">Connection Failed</span>`;
            });
    </script>
</body>
</html>
""")

# Try different import strategies
try:
    # First try explicit import from app
    from app import create_app
    app = create_app()
    logger.info("Successfully created app from app.create_app()")
except Exception as e:
    logger.error(f"Error importing from app: {e}")
    try:
        # Try direct import from wsgi
        from wsgi import app
        logger.info("Successfully imported app from wsgi.py")
    except Exception as e:
        logger.error(f"Error importing from wsgi: {e}")
        try:
            # Try from wsgi_app
            from wsgi_app import application as app
            logger.info("Successfully imported application from wsgi_app")
        except Exception as e:
            logger.error(f"Error importing from wsgi_app: {e}")
            # Create minimal app as last resort
            try:
                from flask import Flask, send_from_directory
                app = Flask(__name__, static_folder='static')

                @app.route('/')
                def home():
                    logger.info("Serving fallback index.html")
                    return send_from_directory(app.static_folder, 'index.html')

                @app.route('/api/health')
                def health():
                    from flask import jsonify
                    return jsonify({"status": "unhealthy", "message": "Emergency fallback app"})

                @app.route('/<path:path>')
                def static_files(path):
                    logger.info(f"Serving static file: {path}")
                    return send_from_directory(app.static_folder, path)

                logger.info("Created fallback app")
            except Exception as e:
                logger.error(f"Failed to create even a fallback app: {e}")
                raise RuntimeError("Could not initialize any Flask application")

# This is the WSGI entry point that gunicorn will use
app = application
