name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'  # Run at 1:30 AM UTC daily

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        # Issue specific settings
        days-before-issue-stale: 60
        days-before-issue-close: 7
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        close-issue-message: >
          This issue has been automatically closed because it has not had recent activity.
          Please feel free to reopen it if you believe it still needs attention.

        # PR specific settings
        days-before-pr-stale: 30
        days-before-pr-close: 7
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        close-pr-message: >
          This pull request has been automatically closed because it has not had recent activity.
          Please feel free to reopen it if you believe it still needs attention.

        # Labels
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'pinned,security,enhancement,bug'
        exempt-pr-labels: 'pinned,security,work-in-progress'

        # Other settings
        exempt-all-milestones: true
        exempt-all-assignees: false
        operations-per-run: 100
        enable-statistics: true
