export const MODAL_TYPES = {
  // Auth modals
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  SETTINGS: "SETTINGS",

  // Universe modals
  CREATE_UNIVERSE: "CREATE_UNIVERSE",
  EDIT_UNIVERSE: "EDIT_UNIVERSE",
  DELETE_UNIVERSE: "DELETE_UNIVERSE",

  // Scene modals
  CREATE_SCENE: "CREATE_SCENE",
  EDIT_SCENE: "EDIT_SCENE",
  DELETE_SCENE: "DELETE_SCENE",

  // Physics modals
  CREATE_PHYSICS_OBJECT: "CREATE_PHYSICS_OBJECT",
  EDIT_PHYSICS_OBJECT: "EDIT_PHYSICS_OBJECT",
  DELETE_PHYSICS_OBJECT: "DELETE_PHYSICS_OBJECT",
  PHYSICS_PARAMETERS: "PHYSICS_PARAMETERS",
  HARMONY_PARAMETERS: "HARMONY_PARAMETERS",

  // Export/Import modals
  EXPORT: "EXPORT",
  IMPORT: "IMPORT",

  // Confirmation modals
  CONFIRM_DELETE: "CONFIRM_DELETE",
  CONFIRM_DISCARD: "CONFIRM_DISCARD",
  CONFIRM_ACTION: "CONFIRM_ACTION",

  // Settings modals
  USER_SETTINGS: "USER_SETTINGS",
  APP_SETTINGS: "APP_SETTINGS",

  // Debug modals
  DEBUG_PANEL: "DEBUG_PANEL",
  ERROR_DETAILS: "ERROR_DETAILS",
};
