export const MODAL_TYPES = {
  // Auth modals
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",

  // Universe modals
  UNIVERSE_CREATE: "UNIVERSE_CREATE",
  UNIVERSE_EDIT: "UNIVERSE_EDIT",
  UNIVERSE_DELETE: "UNIVERSE_DELETE",

  // Scene modals
  SCENE_CREATE: "SCENE_CREATE",
  SCENE_EDIT: "SCENE_EDIT",
  SCENE_DELETE: "SCENE_DELETE",

  // Physics modals
  PHYSICS_OBJECT_CREATE: "PHYSICS_OBJECT_CREATE",
  PHYSICS_OBJECT_EDIT: "PHYSICS_OBJECT_EDIT",
  PHYSICS_OBJECT_DELETE: "PHYSICS_OBJECT_DELETE",
  PHYSICS_PARAMETERS: "PHYSICS_PARAMETERS",

  // Confirmation modals
  CONFIRM_DELETE: "CONFIRM_DELETE",
  CONFIRM_DISCARD: "CONFIRM_DISCARD",
  CONFIRM_ACTION: "CONFIRM_ACTION",

  // Settings modals
  USER_SETTINGS: "USER_SETTINGS",
  APP_SETTINGS: "APP_SETTINGS",

  // Debug modals
  DEBUG_PANEL: "DEBUG_PANEL",
  ERROR_DETAILS: "ERROR_DETAILS",
};
