from .process import process_generation
from .parameter_generation import generate_parameters
from .music_generation import generate_music
from .visualization_generation import generate_visualization
