name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update Frontend Dependencies
        run: |
          cd frontend
          npm outdated
          npm update
          npm audit fix

      - name: Update Backend Dependencies
        run: |
          cd backend
          npm outdated
          npm update
          npm audit fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: '⬆️ Update Dependencies'
          body: |
            This PR updates project dependencies to their latest versions.

            Changes:
            - Updated frontend dependencies
            - Updated backend dependencies

            Please review the changes and test thoroughly before merging.
          branch: 'deps/update'
          base: 'main'
          labels: |
            dependencies
            automated pr
          draft: false
