"""Add username and color fields to User model

Revision ID: 27bc356fe57f
Revises: 60ebacf5d282
Create Date: 2025-02-11 19:36:19.600659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bc356fe57f'
down_revision = '60ebacf5d282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('color', sa.String(length=7), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'color')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
