"""create initial schema

Revision ID: 60ebacf5d282
Revises: 
Create Date: 2025-02-11 19:22:58.178143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60ebacf5d282'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expires', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_expires', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('reset_token'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_table('ai_models',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_type', sa.Enum('AUDIO_GENERATION', 'AUDIO_ANALYSIS', 'PHYSICS_SIMULATION', 'VISUALIZATION', 'CUSTOM', name='modeltype'), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('INITIALIZING', 'TRAINING', 'READY', 'ERROR', 'ARCHIVED', name='modelstatus'), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_models_name'), 'ai_models', ['name'], unique=False)
    op.create_table('datasets',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('dataset_metadata', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('physics_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('harmony_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('story_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visualization_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_results',
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('universe_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('physics_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('harmony_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visualization_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_sessions',
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('validation_results', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('workspace_users',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE')
    )
    op.create_table('activities',
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_files',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('midi_sequences',
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('time_signature', sa.String(), nullable=True),
    sa.Column('is_loop', sa.Boolean(), nullable=True),
    sa.Column('loop_start', sa.Float(), nullable=True),
    sa.Column('loop_end', sa.Float(), nullable=True),
    sa.Column('quantization', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_midi_sequences_name'), 'midi_sequences', ['name'], unique=False)
    op.create_table('physics_objects',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('velocity', sa.JSON(), nullable=True),
    sa.Column('acceleration', sa.JSON(), nullable=True),
    sa.Column('rotation', sa.JSON(), nullable=True),
    sa.Column('angular_velocity', sa.JSON(), nullable=True),
    sa.Column('scale', sa.JSON(), nullable=True),
    sa.Column('is_static', sa.Boolean(), nullable=True),
    sa.Column('is_trigger', sa.Boolean(), nullable=True),
    sa.Column('collision_shape', sa.String(), nullable=True),
    sa.Column('collision_params', sa.JSON(), nullable=True),
    sa.Column('material_properties', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physics_objects_name'), 'physics_objects', ['name'], unique=False)
    op.create_table('physics_parameters',
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('gravity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('air_resistance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collision_elasticity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('friction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('temperature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pressure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fluid_density', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('viscosity', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_step', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('substeps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id')
    )
    op.create_table('project_users',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_table('resources',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_tracks',
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('midi_sequence_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('pan', sa.Float(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('loop_enabled', sa.Boolean(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['midi_sequence_id'], ['midi_sequences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_tracks_name'), 'audio_tracks', ['name'], unique=False)
    op.create_table('midi_events',
    sa.Column('sequence_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.Column('velocity', sa.Integer(), nullable=True),
    sa.Column('control_number', sa.Integer(), nullable=True),
    sa.Column('control_value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sequence_id'], ['midi_sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_midi_events_event_type'), 'midi_events', ['event_type'], unique=False)
    op.create_table('physics_constraints',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('constraint_type', sa.String(), nullable=True),
    sa.Column('object_a_id', sa.UUID(), nullable=True),
    sa.Column('object_b_id', sa.UUID(), nullable=True),
    sa.Column('anchor_a', sa.JSON(), nullable=True),
    sa.Column('anchor_b', sa.JSON(), nullable=True),
    sa.Column('axis_a', sa.JSON(), nullable=True),
    sa.Column('axis_b', sa.JSON(), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('spring_properties', sa.JSON(), nullable=True),
    sa.Column('breaking_force', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['object_a_id'], ['physics_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_b_id'], ['physics_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physics_constraints_name'), 'physics_constraints', ['name'], unique=False)
    op.create_table('visualizations',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('universe_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_automation',
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('parameter_type', sa.Enum('VOLUME', 'PAN', 'EFFECT_PARAM', 'CUSTOM', name='automationtype'), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('points', sa.JSON(), nullable=True),
    sa.Column('curve_type', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['audio_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_markers',
    sa.Column('track_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['audio_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_markers_name'), 'audio_markers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_markers_name'), table_name='audio_markers')
    op.drop_table('audio_markers')
    op.drop_table('audio_automation')
    op.drop_table('visualizations')
    op.drop_index(op.f('ix_physics_constraints_name'), table_name='physics_constraints')
    op.drop_table('physics_constraints')
    op.drop_index(op.f('ix_midi_events_event_type'), table_name='midi_events')
    op.drop_table('midi_events')
    op.drop_index(op.f('ix_audio_tracks_name'), table_name='audio_tracks')
    op.drop_table('audio_tracks')
    op.drop_table('resources')
    op.drop_table('project_users')
    op.drop_table('physics_parameters')
    op.drop_index(op.f('ix_physics_objects_name'), table_name='physics_objects')
    op.drop_table('physics_objects')
    op.drop_index(op.f('ix_midi_sequences_name'), table_name='midi_sequences')
    op.drop_table('midi_sequences')
    op.drop_table('audio_files')
    op.drop_table('activities')
    op.drop_table('workspace_users')
    op.drop_table('user_roles')
    op.drop_table('training_sessions')
    op.drop_table('scenes')
    op.drop_table('projects')
    op.drop_table('inference_results')
    op.drop_table('workspaces')
    op.drop_table('universes')
    op.drop_table('roles')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_ai_models_name'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
