"""add scene_id to physics_parameters

Revision ID: 988e06e770e0
Revises: 424b43a87324
Create Date: 2025-03-03 04:27:10.198704+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "988e06e770e0"
down_revision = "424b43a87324"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "physics_parameters_scene_id_key", "physics_parameters", type_="unique"
    )
    op.drop_constraint(
        "physics_parameters_scene_id_fkey", "physics_parameters", type_="foreignkey"
    )
    op.create_foreign_key(None, "physics_parameters", "scenes", ["scene_id"], ["id"])
    op.drop_column("physics_parameters", "viscosity")
    op.drop_column("physics_parameters", "fluid_density")
    op.drop_column("physics_parameters", "friction")
    op.drop_column("physics_parameters", "time_step")
    op.drop_column("physics_parameters", "is_active")
    op.drop_column("physics_parameters", "temperature")
    op.drop_column("physics_parameters", "substeps")
    op.drop_column("physics_parameters", "pressure")
    op.drop_column("physics_parameters", "version")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "physics_parameters",
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "physics_parameters",
        sa.Column(
            "pressure",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "physics_parameters",
        sa.Column(
            "substeps",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "physics_parameters",
        sa.Column(
            "temperature",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "physics_parameters",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "physics_parameters",
        sa.Column(
            "time_step",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "physics_parameters",
        sa.Column(
            "friction",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "physics_parameters",
        sa.Column(
            "fluid_density",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "physics_parameters",
        sa.Column(
            "viscosity",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "physics_parameters", type_="foreignkey")
    op.create_foreign_key(
        "physics_parameters_scene_id_fkey",
        "physics_parameters",
        "scenes",
        ["scene_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "physics_parameters_scene_id_key", "physics_parameters", ["scene_id"]
    )
    # ### end Alembic commands ###
