"""Add theme to Universe model

Revision ID: 87da1e60eca7
Revises: d542f1014596
Create Date: 2025-03-04 21:35:12.393396+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87da1e60eca7"
down_revision = "d542f1014596"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("universes", sa.Column("theme", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("universes", "theme")
    # ### end Alembic commands ###
