"""Add universe_id to scenes

Revision ID: 7f4d7e1ac84c
Revises: ec53200b54ff
Create Date: 2025-02-03 05:54:07.947644+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = "7f4d7e1ac84c"
down_revision: Union[str, None] = "ec53200b54ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenes",
        sa.Column("universe_id", GUID(length=32), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_scenes_universe_id_universes"),
        "scenes",
        "universes",
        ["universe_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_scenes_universe_id_universes"), "scenes", type_="foreignkey"
    )
    op.drop_column("scenes", "universe_id")
    # ### end Alembic commands ###
