"""Add creator_id to scenes

Revision ID: 2552c5bed35d
Revises: 5f4d7e1ac84c
Create Date: 2025-02-03 05:51:11.503226+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = "2552c5bed35d"
down_revision: Union[str, None] = "5f4d7e1ac84c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scenes",
        sa.Column("creator_id", GUID(length=32), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_scenes_creator_id_users"), "scenes", "users", ["creator_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_scenes_creator_id_users"), "scenes", type_="foreignkey")
    op.drop_column("scenes", "creator_id")
    # ### end Alembic commands ###
