"""create_storyboard_scenes_table

Revision ID: 8ccc555089f4
Revises: 474995466b08
Create Date: 2025-02-03 06:11:38.676350+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = "8ccc555089f4"
down_revision: Union[str, None] = "474995466b08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storyboard_scenes",
        sa.Column("storyboard_id", GUID(length=32), nullable=False),
        sa.Column("scene_id", GUID(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scenes.id"],
            name=op.f("fk_storyboard_scenes_scene_id_scenes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["storyboard_id"],
            ["storyboards.id"],
            name=op.f("fk_storyboard_scenes_storyboard_id_storyboards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "storyboard_id", "scene_id", name=op.f("pk_storyboard_scenes")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storyboard_scenes")
    # ### end Alembic commands ###
