"""Add creator_id to audio_file

Revision ID: ec53200b54ff
Revises: 2552c5bed35d
Create Date: 2025-02-03 05:52:39.947644+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.custom_types import GUID


# revision identifiers, used by Alembic.
revision: str = "ec53200b54ff"
down_revision: Union[str, None] = "2552c5bed35d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audio_file",
        sa.Column("creator_id", GUID(length=32), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_audio_file_creator_id_users"),
        "audio_file",
        "users",
        ["creator_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_audio_file_creator_id_users"), "audio_file", type_="foreignkey"
    )
    op.drop_column("audio_file", "creator_id")
    # ### end Alembic commands ###
