"""add_visualizations_table

Revision ID: 408e9334cc26
Revises: 988e06e770e0
Create Date: 2025-03-03 03:23:48.936189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408e9334cc26'
down_revision = '988e06e770e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualizations', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('visualizations', sa.Column('scene_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'visualizations', 'scenes', ['scene_id'], ['id'], ondelete='CASCADE')
    op.drop_column('visualizations', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visualizations', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'visualizations', type_='foreignkey')
    op.drop_column('visualizations', 'scene_id')
    op.drop_column('visualizations', 'name')
    # ### end Alembic commands ###
