"""add missing columns to physics_parameters table

Revision ID: 424b43a87324
Revises: 4f29b6f1e945
Create Date: 2025-03-02 18:07:27.466117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '424b43a87324'
down_revision = '4f29b6f1e945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physics_parameters', sa.Column('name', sa.String(), nullable=False))
    op.add_column('physics_parameters', sa.Column('description', sa.String(), nullable=True))
    op.add_column('physics_parameters', sa.Column('time_scale', sa.Float(), nullable=True))
    op.add_column('physics_parameters', sa.Column('friction_coefficient', sa.Float(), nullable=True))
    op.add_column('physics_parameters', sa.Column('integration_method', sa.String(), nullable=True))
    op.add_column('physics_parameters', sa.Column('constraint_iterations', sa.Integer(), nullable=True))
    op.add_column('physics_parameters', sa.Column('universe_id', postgresql.UUID(as_uuid=True), nullable=False))

    # Use raw SQL to handle the JSONB to Float conversion
    op.execute('ALTER TABLE physics_parameters ALTER COLUMN gravity TYPE FLOAT USING (gravity->>\'value\')::FLOAT')
    op.execute('ALTER TABLE physics_parameters ALTER COLUMN air_resistance TYPE FLOAT USING (air_resistance->>\'value\')::FLOAT')
    op.execute('ALTER TABLE physics_parameters ALTER COLUMN collision_elasticity TYPE FLOAT USING (collision_elasticity->>\'value\')::FLOAT')

    # The rest of the migration can proceed normally
    op.alter_column('physics_parameters', 'custom_parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('physics_parameters', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('physics_parameters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('physics_parameters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'physics_parameters', 'universes', ['universe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'physics_parameters', type_='foreignkey')
    op.alter_column('physics_parameters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('physics_parameters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('physics_parameters', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('physics_parameters', 'custom_parameters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('physics_parameters', 'collision_elasticity',
               existing_type=sa.Float(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('physics_parameters', 'air_resistance',
               existing_type=sa.Float(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('physics_parameters', 'gravity',
               existing_type=sa.Float(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('physics_parameters', 'universe_id')
    op.drop_column('physics_parameters', 'constraint_iterations')
    op.drop_column('physics_parameters', 'integration_method')
    op.drop_column('physics_parameters', 'friction_coefficient')
    op.drop_column('physics_parameters', 'time_scale')
    op.drop_column('physics_parameters', 'description')
    op.drop_column('physics_parameters', 'name')
    # ### end Alembic commands ###
