"""Initial migration

Revision ID: 64b92dc6fd73
Revises: 
Create Date: 2025-01-14 02:16:44.373398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b92dc6fd73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('universes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gravity_constant', sa.Float(), nullable=True),
    sa.Column('environment_harmony', sa.Float(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('music_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_parameters_instrument'), ['instrument'], unique=False)
        batch_op.create_index(batch_op.f('ix_music_parameters_parameter_name'), ['parameter_name'], unique=False)

    op.create_table('physics_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('physics_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physics_parameters_parameter_name'), ['parameter_name'], unique=False)

    op.create_table('storyboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('universe_id', sa.Integer(), nullable=False),
    sa.Column('plot_point', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('harmony_tie', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storyboards')
    with op.batch_alter_table('physics_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physics_parameters_parameter_name'))

    op.drop_table('physics_parameters')
    with op.batch_alter_table('music_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_parameters_parameter_name'))
        batch_op.drop_index(batch_op.f('ix_music_parameters_instrument'))

    op.drop_table('music_parameters')
    op.drop_table('universes')
    op.drop_table('users')
    # ### end Alembic commands ###
