"""increase password_hash length

Revision ID: 671606b72edd
Revises: e4b5f7c8a9b0
Create Date: 2025-04-16 00:37:10.756060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671606b72edd'
down_revision = 'e4b5f7c8a9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
