"""Add creator_id to universes

Revision ID: b77cec913e0d
Revises:
Create Date: 2025-01-13 12:31:37.003076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77cec913e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.alter_column('gravity_constant',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('environment_harmony',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_foreign_key('fk_universes_creator_id_users', 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_universes_creator_id_users', type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.alter_column('environment_harmony',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('gravity_constant',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
