"""Add not-null constraints to physics_objects fields

Revision ID: d542f1014596
Revises: 408e9334cc26
Create Date: 2025-03-03 04:40:02.082539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd542f1014596'
down_revision = '408e9334cc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('physics_constraints', sa.Column('object1_id', sa.UUID(), nullable=True))
    op.add_column('physics_constraints', sa.Column('object2_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'physics_constraints', 'physics_objects', ['object1_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'physics_constraints', 'physics_objects', ['object2_id'], ['id'], ondelete='CASCADE')
    op.alter_column('physics_objects', 'universe_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('physics_objects', 'scene_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('physics_objects', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('physics_objects', 'position',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('physics_objects', 'rotation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('physics_objects', 'scale',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('physics_objects', 'mass',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('physics_objects', 'velocity',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('physics_objects', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('physics_objects', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('physics_objects', 'velocity',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('physics_objects', 'mass',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('physics_objects', 'scale',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('physics_objects', 'rotation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('physics_objects', 'position',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('physics_objects', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('physics_objects', 'scene_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('physics_objects', 'universe_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'physics_constraints', type_='foreignkey')
    op.drop_constraint(None, 'physics_constraints', type_='foreignkey')
    op.drop_column('physics_constraints', 'object2_id')
    op.drop_column('physics_constraints', 'object1_id')
    # ### end Alembic commands ###
